### ISSUE TITLE
Unable to load sentry-pivotal on sentry 7.6.0

### ISSUE THREAD

**Issue by RaviTezu** [getsentry/sentry-pivotal#11]
Here's the trace from sentry.log: 

Failed to load app 'sentry_pivotal':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/runner.py", line 239, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (python-dateutil 2.4.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('python-dateutil<2'), set(['pyvotal']))

When I tried to install the python-dateutil 1.5 and sentry was not starting and giving out this error: 
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dateutil<3.0.0,>=2.0.0' distribution was not found and is required by sentry

Its a kind of dead lock. Can you please resolve this?

**Comment by dcramer** [comment]
You may try installing from master. The version on GitHub is likely broken and we haven't pushed out releases for many plugins (as we just install from Git shas)

**Comment by RaviTezu** [comment]
@dcramer Thanks for the reply.
I have installed it using: pip install git+https://github.com/getsentry/sentry-pivotal.git

But still no luck, 

Failed to load app 'sentry_pivotal':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/runner.py", line 239, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (python-dateutil 2.4.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('python-dateutil<2'), set(['pyvotal']))

Failed to load plugin 'sentry_pivotal':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/runner.py", line 251, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (python-dateutil 2.4.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('python-dateutil<2'), set(['pyvotal']))

**Comment by dcramer** [comment]
Looks like we fixed pyvotal too:

-e git+https://github.com/getsentry/pyvotal.git@37d4716480e41bf28edf303c20ab38bccdc7c425#egg=pyvotal-dev

**Comment by RaviTezu** [comment]
@dcramer Thanks for looking into this issue. I have got it working :)
